@startuml(id=clean)
skinparam actor {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam agent {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam artifact {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam boundary {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam card {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam circle {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam cloud {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam collections {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam component {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam control {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam database {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam entity {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam file {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam folder {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam frame {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam interface {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam label {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam node {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam package {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam queue {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam rectangle {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam stack {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam storage {
    BackgroundColor #F2F1F0
    BorderColor #000
}
skinparam usecase {
    BackgroundColor #F2F1F0
    BorderColor #000
}
@enduml