@startuml
!include deployment-diagram.puml

'AFD8F2 -> internal
'EDF2F3 -> external

actor actor 
agent agent
artifact artifact
boundary boundary
card card
circle circle
cloud cloud
collections collections
component newComponent <<new>>
component updateComponent <<update>>
control control
database database
entity entity
file file
folder folder
frame frame
interface interface
label label
node node
package package
queue queue
rectangle rectangle
stack stack
storage storage
usecase usecase
@enduml