@startuml
!include deployment-diagram.puml

actor actor

rectangle company <<internal>> {
    component newComponent <<new>>
    component removeComponent <<remove>>
}
rectangle vendor <<external>><<firewalled>> {
    component updateComponent <<update>>
}

actor --> newComponent
newComponent -> updateComponent 

agent agent
artifact artifact
boundary boundary
card card
circle circle
cloud cloud
collections collections
control control
database database
entity entity
file file
folder folder
frame frame
interface interface
label label
node node
package package
queue queue
rectangle rectangle
stack stack
storage storage
usecase usecase
@enduml